-- Generated by robloxPageToEmmy.py

--- GuiBase2d is an abstract class inherited by 2D GUI Objects.
--- 
---@class GuiBase2d
GuiBase2d = {
	-- Properties --
	--- Describes the actual screen position of a UI element, in pixels.
	--- Tags: ReadOnly, NotReplicated
	---@type Vector2
	AbsolutePosition=nil,
	--- Describes the actual screen rotation of a UI element, in degrees.
	--- Tags: ReadOnly, NotReplicated
	---@type number
	AbsoluteRotation=nil,
	--- Describes the actual screen size of a UI element, in pixels.
	--- Tags: ReadOnly, NotReplicated
	---@type Vector2
	AbsoluteSize=nil,
	--- When set to true, localization will be applied to this GuiBase2d and its descendants based on the GuiBase2d/RootLocalizationTable specified for this GuiBase2d.
	---@type boolean
	AutoLocalize=nil,
	--- A reference to a LocalizationTable to be used to apply automated localization to this GuiBase2d and its descendants.
	---@type LocalizationTable
	RootLocalizationTable=nil
}

-- Functions --


-- Events --