-- Generated by robloxPageToEmmy.py

--- A TextButton behaves similarly to TextLabel in regards to rendering with the additional behaviors of a GuiButton. It defines the same text-rendering properties as a TextLabel does.
--- You can disable text rendering by setting TextButton/TextTransparency to 1. This will leave you with a plain rectangle that can be used as a button.
---@class TextButton : GuiButton
TextButton = {
	-- Properties --
	--- Determines the font used to render text.
	---@type Font
	Font=nil,
	--- Scales the spacing between lines of text in the TextButton.
	---@type number
	LineHeight=nil,
	--- Sets whether a TextButton should be GuiBase2d/Localize or not.
	--- Tags: Hidden, ReadOnly, NotReplicated
	---@type string
	LocalizedText=nil,
	--- Determines the string rendered by the UI element.
	---@type string
	Text=nil,
	--- The pixel size of a UI element’s text.
	--- Tags: ReadOnly, NotReplicated
	---@type Vector2
	TextBounds=nil,
	--- Determines the color of rendered text
	---@type Color3
	TextColor3=nil,
	--- A boolean representation of whether the TextButton’s text fits within the size of it.
	--- Tags: ReadOnly, NotReplicated
	---@type boolean
	TextFits=nil,
	--- Changes whether text is resized to fit within the TextButton.
	---@type boolean
	TextScaled=nil,
	--- Determine the line height of text in pixels.
	---@type number
	TextSize=nil,
	--- Determines the color of the text stroke (outline).
	---@type Color3
	TextStrokeColor3=nil,
	--- Determines the transparency of the text stroke (outline).
	---@type number
	TextStrokeTransparency=nil,
	--- Determines the transparency of rendered text.
	---@type number
	TextTransparency=nil,
	--- Controls the truncation of the text displayed in this TextButton.
	---@type TextTruncate
	TextTruncate=nil,
	--- Determines if text wraps to multiple lines within the TextButton|GUI element space, truncating excess text
	---@type boolean
	TextWrapped=nil,
	--- Determines the horizontal alignment of rendered text.
	---@type TextXAlignment
	TextXAlignment=nil,
	--- Determines the vertical alignment of rendered text.
	---@type TextYAlignment
	TextYAlignment=nil
}

-- Functions --


-- Events --