-- Generated by robloxPageToEmmy.py

--- A TextLabel renders a rectangle, like a Frame, with styled text. The rectangle can be used to define text boundaries, text scaling (TextLabel/TextScaled) and wrapping (TextLabel/TextWrapped, TextLabel/TextXAlignment, TextLabel/TextYAlignment).
--- This class contains properties that control the display of the text, such as TextLabel/Font and TextLabel/TextColor3. All text rendered by a single text label will have the same visual properties; multiple TextLabel objects must be used in order to render multiple styles of text. To display only text and hide the rectangle, set GuiObject/BackgroundTransparency to 1.
--- TextService/GetTextSize can be used to get the size (bounds) of text that would be rendered in a TextLabel given a font size, font, and frame size.
--- A UITextSizeConstraint object can be used to constrain the size of text with TextLabel/TextScaled enabled.
---@class TextLabel : GuiLabel
TextLabel = {
	-- Properties --
	--- Determines the font used to render text.
	---@type Font
	Font=nil,
	--- Scales the spacing between lines of text in the TextLabel.
	---@type number
	LineHeight=nil,
	--- Sets whether a TextLabel should be GuiBase2d/Localize or not.
	--- Tags: Hidden, ReadOnly, NotReplicated
	---@type string
	LocalizedText=nil,
	--- Determines the string rendered by the UI element.
	---@type string
	Text=nil,
	--- The pixel size of a UI element’s text.
	--- Tags: ReadOnly, NotReplicated
	---@type Vector2
	TextBounds=nil,
	--- This property determines the color of rendered text
	---@type Color3
	TextColor3=nil,
	--- Enables when rendered text content does not fit within the UI element’s space.
	--- Tags: ReadOnly, NotReplicated
	---@type boolean
	TextFits=nil,
	--- Determines whether text in a UI element is scaled to fill the UI element.
	---@type boolean
	TextScaled=nil,
	--- Determine the line height of text in pixels.
	---@type number
	TextSize=nil,
	--- Determines the color of the text stroke (outline).
	---@type Color3
	TextStrokeColor3=nil,
	--- Determines the transparency of the text stroke (outline).
	---@type number
	TextStrokeTransparency=nil,
	--- Determines the transparency of rendered text.
	---@type number
	TextTransparency=nil,
	--- Controls the truncation of the text displayed in this TextLabel.
	---@type TextTruncate
	TextTruncate=nil,
	--- Determines if text wraps to multiple lines within the TextLabel|GUI element space, truncating excess text.
	---@type boolean
	TextWrapped=nil,
	--- Determines the horizontal alignment of rendered text.
	---@type TextXAlignment
	TextXAlignment=nil,
	--- Determines the vertical alignment of rendered text.
	---@type TextYAlignment
	TextYAlignment=nil
}

-- Functions --


-- Events --